<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container49v0nx1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container49v0nx1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container49v0nx1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container49v0nx1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container49v0nx1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '49v0nx1',
    'container.build_id' => 'eec8f47f',
    'container.build_time' => 1558970654,
], __DIR__.\DIRECTORY_SEPARATOR.'Container49v0nx1');
