<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIJtV2ra\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIJtV2ra/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIJtV2ra.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIJtV2ra\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIJtV2ra\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IJtV2ra',
    'container.build_id' => '97195f45',
    'container.build_time' => 1559057040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIJtV2ra');
