<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFUTffNj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFUTffNj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFUTffNj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFUTffNj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFUTffNj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FUTffNj',
    'container.build_id' => '4df73b21',
    'container.build_time' => 1559045929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFUTffNj');
